# Generated by Django 3.1.4 on 2020-12-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20201222_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='albums',
            field=models.ManyToManyField(to='image.Album'),
        ),
    ]
